housePower<-read.table("household_power_consumption.txt", sep = ";", strip.white=TRUE, stringsAsFactors=FALSE, dec = ".", header = TRUE)
housePower$Date<-as.Date(housePower$Date, "%d/%m/%Y")
requiredData<-subset(housePower, Date>=as.Date("2007-02-01") & Date<=as.Date("2007-02-02"))
dateTime<-paste(requiredData$Date,requiredData$Time)
dateTime<-as.POSIXlt(dateTime)
sm1<-as.numeric(requiredData$Sub_metering_1)
sm2<-as.numeric(requiredData$Sub_metering_2)
sm3<-as.numeric(requiredData$Sub_metering_3)
png("plot3.png", width=480, height=480)
plot(dateTime, sm1, type = "l", xlab = "", ylab = "Energy sub metering")
points(dateTime, sm2, type = "l", col="red")
points(dateTime, sm3, type = "l", col="blue")
legend("topright", c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), lty=1, lwd=2.5, col=c("black", "red", "blue"))
dev.off()